POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
        "content": "Mi primera nota",
        "important": true,
        "userId": "66060a0be008d6d3e2ca0474"
}


###

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
}